baseURL = "http://localhost:2002/"
languageCode = 'en-us'
title = 'SHXLPA'
theme = 'Typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "SHILPA's projects"

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = "I'm Shilpa, a musician & electrical engineer from LA."
homeIntroContent = """
This is a newsletter for my network. 

I post about my projects, including but not limited to DIY instruments, microcontrollers, audio production, woodworking, and full-stack software/hardware development.

UCLA ECE '24
"""

# Collection to display on home
homeCollectionTitle = 'Projects'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"

[[params.social]]
name = "medium"
url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Projects"
url = "/posts"

[[params.menu]]
name = "Contact"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"